# docker-compose.yml
version: "2"
services:
  app:
    container_name: generar_ticket_texcargo
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 app.py
    volumes:
      - /usr/local/volumes/generar_ticket_texcargo/fileserver/:/app/fileserver/
    ports:
      - "4545:4545"